source 'https://rubygems.org'

gem 'rails', '3.2.8'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mongoid'
gem 'json'
gem 'mongoid-paperclip', :require => 'mongoid_paperclip'
gem 'bcrypt-ruby'
gem 'ruby-stemmer'

group :test, :development do
  gem 'rspec'
  gem 'rspec-rails'
  gem 'minitest'
  gem 'minitest-reporters', '>= 0.5.0'
  gem 'factory_girl_rails', '~> 4.0'
  gem 'linecache19', :git => 'git://github.com/mark-moseley/linecache'
  gem 'ruby-debug-base19x', '~> 0.11.30.pre4'
  gem 'ruby-debug19'
  gem 'ruby-debug-ide', '>= 0.4.17.beta14'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

#front-end gems
gem 'bootstrap-sass'
gem 'simple_form'
gem 'paperclip', '~> 3.0'


# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
